name: Java CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on Java ${{ matrix.java_version }} and OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: ['11', '17', '21']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1.4.3
      with:
        java-version: ${{ matrix.java_version }}
    - name: Main build using Felix
      run: ./mvnw clean install -B -Pfelix -Pjava8
    - name: Main build using Equinox
      run: ./mvnw clean install -B -Pequinox -Pjava8
    - name: Build Android App
      if: matrix.java_version == '11' && matrix.os == 'ubuntu-latest'
      run: |
        cp atomos.examples/atomos.examples.index/target/org.apache.felix.atomos.examples.index-*.jar atomos.examples/atomos.examples.android/app/libs
        atomos.examples/atomos.examples.android/gradlew -b atomos.examples/atomos.examples.android/build.gradle build

